tubes:
  root: '/home/pi/d2/data'
models:
  root: '/home/pi/models'
car:
  path: '/home/pi/d2'
  cwd: '/home/pi'
  remote:
    channels:
      steering: 18
      throttle: 23
      mode: 22
  actuator:
    steeringChannel: 1
    throttleChannel: 0
    throttleMax: 425
    remoteThrottleMax: 475
    throttleMin: 300
    remoteThrottleMin: 490
  autopilot:
    pythonPath: '/home/pi/.virtualenvs/dk/bin/python3'
    scripts_path: 'python'
    pilot: 
      script: 'autopilot.py'
      interval: 50
    recorder:
      script: 'recorder.py'
      interval: 50
