tubes:
  root: '/home/pi/d2/data'
models:
  root: '/home/pi/models'
api:
  baseUrl: 'http://localhost:8887'
car:
  path: '/home/pi/d2'
  cwd: '/home/pi'
  pythonPath: '/home/pi/.virtualenvs/dk/bin/python3'
configServer:
  bind: 'tcp://*:5556'
training:
  slide: '2'
  enhance_image_count: '50000'