tubes:
  root: '/home/pi/d2/data'
models:
  root: '/home/pi/models'
car:
  path: '/home/pi/d2'
  cwd: '/home/pi'
  timerPin: 17
  remote:
    channels:
      steering: 18
      throttle: 23
      mode: 22
  actuator:
    steeringChannel: 1
    throttleChannel: 0
    throttleMax: 380
    remoteThrottleMax: 475
    throttleMin: 300
    remoteThrottleMin: 490
    steeringMax: 1900
    steeringMin: 1100
  autopilot:
    pythonPath: '/home/pi/.virtualenvs/dk/bin/python3'
    scripts_path: 'python'
    script: 'autopilot.py'
    interval: 50
  statusLed:
    red: 21
    green: 20
    blue: 19
